# CREATE DATABASE → SQL command used to create a new database.
# sales_analysis_project name of the database where your project data will be stored.
CREATE DATABASE sales_analysis_project;

#USE → tells MySQL that all further queries should run inside this database.
USE sales_analysis_project;

#Create a table to store dataset.
CREATE TABLE sales(
Order_id VARCHAR(50),
Order_date DATE,
Customer_name VARCHAR(100),
region VARCHAR(50),
category VARCHAR(50),
sales FLOAT,
profit FLOAT 
);

SELECT * FROM cleaned_superstore
LIMIT 10;

# Query 1: Total Sales.
SELECT SUM(sales) AS total_sales
FROM cleaned_superstore; # SUM(Sales) = adds all sales values.And it will give u total comapny revenue.

# Query 2 — Total Profit.
SELECT SUM(profit) AS total_profit
FROM cleaned_superstore; #Calculates overall profit generated by the company.

# Query 3 — Sales by Region.
SELECT region,SUM(sales) AS total_sales
FROM cleaned_superstore
GROUP BY region; #GROUP BY Region Groups sales data for each region.

# Query 4 — Top 5 Customers.
SELECT `Customer name`,SUM(sales) AS Total_sales
FROM cleaned_superstore
GROUP BY `Customer name`
ORDER BY total_sales DESC 
LIMIT 5;
-- GROUP BY Customer Name
  #Calculates total purchase per customer.

-- ORDER BY total_sales DESC
  #Sorts from highest to lowest.

-- LIMIT 5
  # Shows top 5 customers.

# Query 5 — Sales by Category.
SELECT category, SUM(sales) AS Total_sales
FROM cleaned_superstore
GROUP BY category; #Groups revenue by product category.

# Query 6 — Monthly Sales Trend.

ALTER TABLE cleaned_superstore
MODIFY `Order Date` DATE;

SELECT MONTH(`Order Date`) AS month,
SUM(Sales) AS total_sales
FROM cleaned_superstore
GROUP BY MONTH(`Order Date`)
ORDER BY MONTH(`Order Date`);
#MONTH(\Order Date`)` correctly extracted months 1–12
#SUM(Sales) correctly calculated total sales per month
#GROUP BY MONTH(\Order Date`)` grouped the data properly.

# Query 7 — Top 5 Products by Sales.
SELECT `Product Name`,
SUM(Sales) AS total_sales
FROM cleaned_superstore
GROUP BY `Product Name`
ORDER BY total_sales DESC
LIMIT 5;
# Groups sales by product
# Sorts products from highest to lowest sales
# Shows top 5 best-selling products

# Query 8 — Sales by Segment.

SELECT segment, SUM(sales) AS total_sales 
FROM cleaned_superstore
GROUP BY segment; # This shows which customer segment generates the most revenue.

# Query 9 — Average Sales per Order.
SELECT AVG(sales) AS avg_sales
FROM cleaned_superstore; # AVG() calculates the average value of orders.

# Query 10 — Profit by Region.
SELECT region, SUM(profit) AS total_profit
FROM cleaned_superstore
GROUP BY region
ORDER BY total_profit DESC; # Shows which region generates the highest profit, not just sales.

# SQL Project Queries :
-- View dataset
-- Total Sales
-- Total Profit
-- Sales by Region
-- Top Customers
-- Sales by Category
-- Monthly Sales Trend
-- Top Products
-- Sales by Segment
-- Profit by Region
-- Average Sales per Order

